import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import {useRouter} from 'next/router'

export default function Home() {
  const router = useRouter()
  console.log(router);
  return (
    <div className={styles.container}>
      <Head>
        <title>Liberto Medina Ramírez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav>
          <Link href="/about-me">
            <a>
              About me
            </a>
          </Link>
        </nav>
        <h1 className={styles.title}>
          Liberto Medina
        </h1>
        <h3>JUNIOR WEB DEVELOPER</h3>
      </main>
    </div>
  )
}
